name: gas_track
description: A new Flutter project.
publish_to: 'none'
version: 0.1.4

environment:
  sdk: '>=2.19.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.5
  intl: ^0.19.0
  shared_preferences: ^2.2.1
  cunning_document_scanner: ^1.1.4
  dotted_border: ^2.1.0
  sizer: ^2.0.15
  firebase_core: ^2.31.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.4

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  android: true

flutter_native_splash:
  color: "#ffffff"
  branding: assets/images/logo.png
  branding_mode: bottom
  android_12:
    branding: assets/images/logo.png
    android_gravity: bottom
    color: "#ffffff"



flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

fonts:
  - family: Bebas
    fonts:
      - assets/fonts/BebasNeue-Regular.ttf
