name: gas_track
description: A new Flutter project.
publish_to: 'none'
version: 0.1.10

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.5
  intl: ^0.19.0
  shared_preferences: ^2.2.1
  cunning_document_scanner: ^1.1.4
  dotted_border: ^2.1.0
  sizer: ^2.0.15
  firebase_core: ^2.31.0
  flutter_launcher_icons: ^0.13.1
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  internet_connection_checker_plus: ^1.0.1
  flutter_secure_storage: ^9.2.2
  openvpn_flutter: ^1.3.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
 

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  android: true





flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vpn/

fonts:
  - family: Bebas
    fonts:
      - assets/fonts/BebasNeue-Regular.ttf
