name: gasolina
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.5
  intl: ^0.18.1
  shared_preferences: ^2.2.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

fonts:
  - family: Bebas
    fonts:
      - assets/fonts/BebasNeue-Regular.ttf
