name: gas_track
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  provider: ^6.0.5
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.4
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.24.3
  mockito: ^5.4.3
  build_runner: ^2.4.6

flutter_launcher_icons:
  image_path: "assets/images/icon.png"
  android: true

flutter_native_splash:
  color: "#ffffff"
  branding: assets/images/logo.png
  branding_mode: bottom
  android_12:
    branding: assets/images/logo.png
    android_gravity: bottom
    color: "#ffffff"



flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

fonts:
  - family: Bebas
    fonts:
      - assets/fonts/BebasNeue-Regular.ttf
